# Generated by Django 6.0.6 on 2026-08-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_email_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
